version: '3'
services:
  offer-core-service:
    image: allezon/offer-core-service:0.9
    container_name: offer-core-service
    ports:
      - "8080:8080"
    environment:
      - KAFKA_PRODUCER_BOOTSTRAP=kafka:9092
      - KAFKA_OFFER_CHANGE_TOPIC=offerChange
      - POSTGRES_HOST=offer-core-db
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=offers  
    depends_on: 
      - offer-core-db
    restart: on-failure:3
  offer-core-db:
    image: postgres
    container_name: offer-core-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=offers
    volumes:
      - offer-core-data:/var/lib/postgresql/data

  offer-store-service:
    image: allezon/offer-store-service:0.8
    container_name: offer-store-service
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CONSUMER_BOOTSTRAP=kafka:9092
      - KAFKA_CONSUMER_TOPIC=offerChange
      - MONGODB_HOST=offer-store-db
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=offers
    depends_on:
      - offer-store-db
    restart: on-failure:3
  offer-store-db:
    image: bitnami/mongodb:latest
    container_name: offer-store-db
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=offers
    volumes:
      - offer-store-data:/bitnami

  offer-search-service:
    image: allezon/offer-search-service:0.8
    container_name: offer-search-service
    ports:
      - "8082:8080"
    environment:
      - KAFKA_CONSUMER_BOOTSTRAP=kafka:9092
      - KAFKA_CONSUMER_TOPIC=offerChange
      - ES_CLUSTER_NAME=offer-search-cluster
      - ES_HOST=offer-search-db
      - ES_PORT=9300
    depends_on:
      - offer-search-db
  offer-search-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    container_name: offer-search-db
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - offer-search-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=offer-search-cluster
      - bootstrap.memory_lock=true
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=offerChange:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: on-failure:10

volumes:
  offer-core-data:
  offer-store-data:
  offer-search-data:
