kafka:
  consumer:
    bootstrap: kafka:9092
    topic: offerChange
    group: offer-store-group
spring:
  data:
    mongodb:
      host: offer-store-db
      port: 27017
      username: admin
      password: admin
      database: offers
